from __future__ import annotations

from collections.abc import Callable
from typing import Any

from onec_hbk_bsl.analysis.diagnostic.bslls_runtime.context import BsllsDocumentContext
from onec_hbk_bsl.analysis.diagnostic.bslls_runtime.rules import (
    AssignAliasFieldsInQueryRule,
    BadWordsRule,
    BeginTransactionBeforeTryCatchRule,
    BsllsDiagnosticRule,
    CanonicalSpellingKeywordsRule,
    CodeBlockBeforeSubRule,
    CommitTransactionOutsideTryCatchRule,
    CommonModuleDiagnosticsRule,
    ConsecutiveEmptyLinesRule,
    DeprecatedCurrentDateRule,
    DeprecatedFindRule,
    DeprecatedMessageRule,
    DeprecatedMethods8310Rule,
    DeprecatedMethods8317Rule,
    DeprecatedTypeManagedFormRule,
    DisableSafeModeRule,
    DoubleNegativesRule,
    EmptyStatementRule,
    EngineBridgeRule,
    ExecuteExternalCodeInCommonModuleRule,
    ExecuteExternalCodeRule,
    ExternalAppStartingRule,
    ExtraCommasRule,
    FileSystemAccessRule,
    GetFormMethodRule,
    IfElseDuplicatedCodeBlockRule,
    IfElseDuplicatedConditionRule,
    IfElseIfEndsWithElseRule,
    IncorrectLineBreakRule,
    InternetAccessRule,
    IsInRoleMethodRule,
    LogicalOrInTheWhereSectionOfQueryRule,
    MagicDateRule,
    MethodContractDiagnosticsRule,
    MissingTemporaryFileDeletionRule,
    NestedTernaryOperatorRule,
    NumberOfValuesInStructureConstructorRule,
    OneStatementPerLineRule,
    OSUsersMethodRule,
    PairingBrokenTransactionRule,
    QueryJoinDiagnosticsRule,
    QueryMetadataDiagnosticsRule,
    QueryTextDiagnosticsRule,
    SetPrivilegedModeRule,
    SpaceAtStartCommentRule,
    TempFilesDirRule,
    TryNumberRule,
    UnaryPlusInConcatenationRule,
    UnionAllRule,
    UsageWriteLogEventRule,
    UseLessForEachRule,
    UselessTernaryOperatorRule,
    UseSystemInformationRule,
    UsingExternalCodeToolsRule,
    UsingGotoRule,
    UsingHardcodeNetworkAddressRule,
    UsingHardcodePathRule,
    UsingServiceTagRule,
    UsingSynchronousCallsRule,
    VirtualTableCallWithoutParametersRule,
    WrongUseFunctionProceedWithCallRule,
    WrongUseOfRollbackTransactionMethodRule,
    YoLetterUsageRule,
)
from onec_hbk_bsl.analysis.diagnostic.models import Diagnostic

_RULES: tuple[BsllsDiagnosticRule, ...] = (
    EngineBridgeRule("BSL001"),
    EngineBridgeRule("BSL002"),
    EngineBridgeRule("BSL003"),
    EngineBridgeRule("BSL004"),
    EngineBridgeRule("BSL007"),
    EngineBridgeRule("BSL008"),
    EngineBridgeRule("BSL009"),
    EngineBridgeRule("BSL011"),
    EngineBridgeRule("BSL012"),
    EngineBridgeRule("BSL013"),
    EngineBridgeRule("BSL014"),
    EngineBridgeRule("BSL015"),
    EngineBridgeRule("BSL016"),
    EngineBridgeRule("BSL017"),
    EngineBridgeRule("BSL019"),
    EngineBridgeRule("BSL020"),
    EngineBridgeRule("BSL022"),
    EngineBridgeRule("BSL026"),
    EngineBridgeRule("BSL028"),
    EngineBridgeRule("BSL029"),
    EngineBridgeRule("BSL030"),
    EngineBridgeRule("BSL031"),
    EngineBridgeRule("BSL032"),
    EngineBridgeRule("BSL033"),
    EngineBridgeRule("BSL035"),
    EngineBridgeRule("BSL036"),
    EngineBridgeRule("BSL040"),
    EngineBridgeRule("BSL042"),
    EngineBridgeRule("BSL051"),
    EngineBridgeRule("BSL052"),
    EngineBridgeRule("BSL054"),
    EngineBridgeRule("BSL062"),
    EngineBridgeRule("BSL064"),
    EngineBridgeRule("BSL065"),
    EngineBridgeRule("BSL077"),
    EngineBridgeRule("BSL131"),
    EngineBridgeRule("BSL148"),
    CommonModuleDiagnosticsRule("BSL152"),
    CommonModuleDiagnosticsRule("BSL154"),
    CommonModuleDiagnosticsRule("BSL156"),
    CommonModuleDiagnosticsRule("BSL158"),
    CommonModuleDiagnosticsRule("BSL159"),
    CommonModuleDiagnosticsRule("BSL160"),
    CommonModuleDiagnosticsRule("BSL161"),
    CommonModuleDiagnosticsRule("BSL162"),
    CommonModuleDiagnosticsRule("BSL163"),
    CommonModuleDiagnosticsRule("BSL164"),
    CommonModuleDiagnosticsRule("BSL165"),
    CommonModuleDiagnosticsRule("BSL166"),
    CommonModuleDiagnosticsRule("BSL167"),
    CommonModuleDiagnosticsRule("BSL168"),
    EngineBridgeRule("BSL171"),
    CommonModuleDiagnosticsRule("BSL172"),
    CommonModuleDiagnosticsRule("BSL173"),
    EngineBridgeRule("BSL169"),
    EngineBridgeRule("BSL170"),
    EngineBridgeRule("BSL181"),
    EngineBridgeRule("BSL182"),
    EngineBridgeRule("BSL196"),
    EngineBridgeRule("BSL260"),
    QueryMetadataDiagnosticsRule("BSL174"),
    EngineBridgeRule("BSL175"),
    EngineBridgeRule("BSL176"),
    QueryMetadataDiagnosticsRule("BSL187"),
    QueryMetadataDiagnosticsRule("BSL189"),
    EngineBridgeRule("BSL190"),
    QueryTextDiagnosticsRule("BSL191"),
    MethodContractDiagnosticsRule("BSL192"),
    MethodContractDiagnosticsRule("BSL193"),
    MethodContractDiagnosticsRule("BSL194"),
    QueryTextDiagnosticsRule("BSL201"),
    EngineBridgeRule("BSL202"),
    EngineBridgeRule("BSL204"),
    QueryJoinDiagnosticsRule("BSL206"),
    QueryJoinDiagnosticsRule("BSL207"),
    EngineBridgeRule("BSL208"),
    QueryJoinDiagnosticsRule("BSL209"),
    QueryMetadataDiagnosticsRule("BSL211"),
    QueryMetadataDiagnosticsRule("BSL213"),
    QueryMetadataDiagnosticsRule("BSL214"),
    MethodContractDiagnosticsRule("BSL212"),
    MethodContractDiagnosticsRule("BSL215"),
    EngineBridgeRule("BSL216"),
    EngineBridgeRule("BSL217"),
    EngineBridgeRule("BSL219"),
    QueryTextDiagnosticsRule("BSL220"),
    EngineBridgeRule("BSL221"),
    EngineBridgeRule("BSL222"),
    EngineBridgeRule("BSL223"),
    MethodContractDiagnosticsRule("BSL224"),
    MethodContractDiagnosticsRule("BSL228"),
    EngineBridgeRule("BSL229"),
    QueryMetadataDiagnosticsRule("BSL231"),
    QueryMetadataDiagnosticsRule("BSL232"),
    MethodContractDiagnosticsRule("BSL233"),
    EngineBridgeRule("BSL234"),
    QueryTextDiagnosticsRule("BSL235"),
    QueryMetadataDiagnosticsRule("BSL236"),
    EngineBridgeRule("BSL237"),
    QueryMetadataDiagnosticsRule("BSL238"),
    EngineBridgeRule("BSL239"),
    MethodContractDiagnosticsRule("BSL240"),
    QueryMetadataDiagnosticsRule("BSL241"),
    QueryMetadataDiagnosticsRule("BSL242"),
    EngineBridgeRule("BSL243"),
    EngineBridgeRule("BSL244"),
    EngineBridgeRule("BSL245"),
    QueryMetadataDiagnosticsRule("BSL246"),
    EngineBridgeRule("BSL248"),
    EngineBridgeRule("BSL249"),
    EngineBridgeRule("BSL251"),
    EngineBridgeRule("BSL252"),
    EngineBridgeRule("BSL253"),
    MethodContractDiagnosticsRule("BSL254"),
    EngineBridgeRule("BSL256"),
    EngineBridgeRule("BSL261"),
    EngineBridgeRule("BSL259"),
    EngineBridgeRule("BSL266"),
    EngineBridgeRule("BSL268"),
    QueryTextDiagnosticsRule("BSL269"),
    QueryMetadataDiagnosticsRule("BSL274"),
    EngineBridgeRule("BSL271"),
    EngineBridgeRule("BSL275"),
    EngineBridgeRule("BSL278"),
    UsingHardcodeNetworkAddressRule(),
    UsingHardcodePathRule(),
    UsingServiceTagRule(),
    BadWordsRule(),
    AssignAliasFieldsInQueryRule(),
    BeginTransactionBeforeTryCatchRule(),
    CodeBlockBeforeSubRule(),
    SpaceAtStartCommentRule(),
    EmptyStatementRule(),
    UsingGotoRule(),
    DoubleNegativesRule(),
    CanonicalSpellingKeywordsRule(),
    DeprecatedMessageRule(),
    NestedTernaryOperatorRule(),
    MagicDateRule(),
    ConsecutiveEmptyLinesRule(),
    DeprecatedFindRule(),
    DeprecatedCurrentDateRule(),
    DeprecatedMethods8310Rule(),
    DeprecatedMethods8317Rule(),
    GetFormMethodRule(),
    DeprecatedTypeManagedFormRule(),
    DisableSafeModeRule(),
    IfElseDuplicatedCodeBlockRule(),
    IfElseDuplicatedConditionRule(),
    IfElseIfEndsWithElseRule(),
    ExecuteExternalCodeRule(),
    ExecuteExternalCodeInCommonModuleRule(),
    ExternalAppStartingRule(),
    IncorrectLineBreakRule(),
    FileSystemAccessRule(),
    InternetAccessRule(),
    IsInRoleMethodRule(),
    UseSystemInformationRule(),
    OSUsersMethodRule(),
    SetPrivilegedModeRule(),
    TempFilesDirRule(),
    UsingExternalCodeToolsRule(),
    UsingSynchronousCallsRule(),
    LogicalOrInTheWhereSectionOfQueryRule(),
    CommitTransactionOutsideTryCatchRule(),
    UseLessForEachRule(),
    VirtualTableCallWithoutParametersRule(),
    NumberOfValuesInStructureConstructorRule(),
    OneStatementPerLineRule(),
    MissingTemporaryFileDeletionRule(),
    PairingBrokenTransactionRule(),
    TryNumberRule(),
    UnaryPlusInConcatenationRule(),
    UnionAllRule(),
    UsageWriteLogEventRule(),
    WrongUseFunctionProceedWithCallRule(),
    WrongUseOfRollbackTransactionMethodRule(),
    ExtraCommasRule(),
    UselessTernaryOperatorRule(),
    YoLetterUsageRule(),
)
BSL_RUNTIME_RULE_CODES: frozenset[str] = frozenset(rule.code for rule in _RULES)
_NATIVE_RUNTIME_RULE_CODES: frozenset[str] = frozenset(
    rule.code for rule in _RULES if not isinstance(rule, EngineBridgeRule)
)


def append_bslls_runtime_rule_tasks(
    rule_tasks: list[tuple[str, Callable[[], list[Diagnostic]]]],
    *,
    engine: Any,
    path: str,
    content: str,
    lines: list[str],
    tree: Any,
    snapshot: Any | None,
) -> None:
    context = BsllsDocumentContext(
        path=path,
        content=content,
        lines=lines,
        tree=tree,
        snapshot=snapshot,
        max_bool_ops=int(getattr(engine, "max_bool_ops", 3)),
        bsl036_enabled=bool(engine._rule_enabled("BSL036")),
        runtime_call_context=(
            engine._runtime_call_context(tree, lines)
            if engine._rule_enabled("BSL255")
            or engine._rule_enabled("BSL276")
            or engine._rule_enabled("BSL277")
            or engine._rule_enabled("BSL262")
            else None
        ),
        ts_nodes_for_types=engine._ts_nodes_for_types,
        global_method_calls_from_nodes=engine._global_method_calls_from_nodes,
        diagnostics_engine=engine,
    )
    for rule in _RULES:
        if isinstance(rule, EngineBridgeRule) and rule.code in _NATIVE_RUNTIME_RULE_CODES:
            continue
        if engine._rule_enabled(rule.code):
            rule_tasks.append((rule.code, lambda rule=rule: rule.run(context)))
